"""original demo schema"""
revision="0001";down_revision=None;branch_labels=None;depends_on=None
from alembic import op
import sqlalchemy as sa

def upgrade():
    op.create_table("leads",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_token",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(100)),sa.Column("name",sa.String(100),nullable=False),sa.Column("company",sa.String(160),nullable=False),sa.Column("email",sa.String(200),nullable=False),sa.Column("industry",sa.String(120),nullable=False),sa.Column("country",sa.String(120),nullable=False),sa.Column("website",sa.String(300)),sa.Column("interested_service",sa.String(160),nullable=False),sa.Column("initial_requirement",sa.Text()),sa.Column("source",sa.String(30),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("lead_score",sa.Integer(),nullable=False),sa.Column("intent",sa.String(20),nullable=False),sa.Column("score_reason",sa.Text(),nullable=False),sa.Column("recommended_service",sa.String(160)),sa.Column("next_action",sa.String(40),nullable=False),sa.Column("conversation_summary",sa.Text(),nullable=False),sa.Column("human_takeover",sa.Boolean(),nullable=False),sa.Column("manual_status",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("last_contacted_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("public_token"),sa.UniqueConstraint("idempotency_key"))
    op.create_index("ix_leads_public_token","leads",["public_token"])
    op.create_table("lead_profiles",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("lead_id",sa.Integer(),sa.ForeignKey("leads.id"),unique=True,nullable=False),*[sa.Column(x,sa.Text()) for x in ["target_market","current_acquisition","current_seo_geo","target_platforms","target_result","pain_points","budget_range","timeline","decision_role"]],sa.Column("has_website",sa.Boolean()),sa.Column("additional_facts",sa.JSON(),nullable=False),sa.Column("missing_fields",sa.JSON(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("messages",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("lead_id",sa.Integer(),sa.ForeignKey("leads.id"),nullable=False),sa.Column("role",sa.String(20),nullable=False),sa.Column("content",sa.Text(),nullable=False),sa.Column("client_message_id",sa.String(100)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("model_name",sa.String(100)),sa.Column("model_latency_ms",sa.Integer()),sa.Column("error_code",sa.String(80)),sa.UniqueConstraint("lead_id","client_message_id"))
    op.create_table("ai_decisions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("lead_id",sa.Integer(),sa.ForeignKey("leads.id"),nullable=False),sa.Column("lead_score",sa.Integer(),nullable=False),sa.Column("intent",sa.String(20),nullable=False),sa.Column("score_breakdown",sa.JSON(),nullable=False),sa.Column("score_reason",sa.Text(),nullable=False),sa.Column("recommended_service",sa.String(160)),sa.Column("next_action",sa.String(40),nullable=False),sa.Column("suggested_status",sa.String(30),nullable=False),sa.Column("should_offer_meeting",sa.Boolean(),nullable=False),sa.Column("should_handoff",sa.Boolean(),nullable=False),sa.Column("handoff_reason",sa.Text()),sa.Column("raw_response_redacted",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("appointments",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("lead_id",sa.Integer(),sa.ForeignKey("leads.id"),nullable=False),sa.Column("start_time",sa.DateTime(timezone=True),nullable=False),sa.Column("end_time",sa.DateTime(timezone=True),nullable=False),sa.Column("timezone",sa.String(80),nullable=False),sa.Column("attendee_name",sa.String(100),nullable=False),sa.Column("attendee_email",sa.String(200),nullable=False),sa.Column("notes",sa.Text()),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("lead_id","start_time"))
    op.create_index("ix_appointments_start_time","appointments",["start_time"])
    op.create_table("activity_logs",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("lead_id",sa.Integer(),sa.ForeignKey("leads.id")),sa.Column("event_type",sa.String(80),nullable=False),sa.Column("message",sa.Text(),nullable=False),sa.Column("metadata",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))

def downgrade():
    for name in ["activity_logs","appointments","ai_decisions","messages","lead_profiles","leads"]:op.drop_table(name)
