"""audit integrations followups and atomic slots"""
revision="0002";down_revision="0001";branch_labels=None;depends_on=None
from alembic import op
import sqlalchemy as sa

def upgrade():
    op.create_table("availability_slots",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("resource_id",sa.String(80),nullable=False),sa.Column("start_time",sa.DateTime(timezone=True),nullable=False),sa.Column("end_time",sa.DateTime(timezone=True),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("held_by_lead_id",sa.Integer(),sa.ForeignKey("leads.id")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("resource_id","start_time"))
    op.create_index("ix_availability_slots_start_time","availability_slots",["start_time"]);op.create_index("ix_availability_slots_status","availability_slots",["status"])
    op.create_table("ai_invocations",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("lead_id",sa.Integer(),sa.ForeignKey("leads.id")),sa.Column("request_id",sa.String(100),nullable=False,unique=True),sa.Column("provider",sa.String(40),nullable=False),sa.Column("model_name",sa.String(100),nullable=False),sa.Column("prompt_version",sa.String(40),nullable=False),sa.Column("input_message_ids",sa.JSON(),nullable=False),sa.Column("knowledge_refs",sa.JSON(),nullable=False),sa.Column("validation_status",sa.String(30),nullable=False),sa.Column("repair_attempts",sa.Integer(),nullable=False),sa.Column("latency_ms",sa.Integer()),sa.Column("input_tokens",sa.Integer()),sa.Column("output_tokens",sa.Integer()),sa.Column("error_type",sa.String(80)),sa.Column("response_summary",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_ai_invocations_lead_id","ai_invocations",["lead_id"])
    op.create_table("lead_status_history",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("lead_id",sa.Integer(),sa.ForeignKey("leads.id"),nullable=False),sa.Column("from_status",sa.String(30)),sa.Column("to_status",sa.String(30),nullable=False),sa.Column("actor",sa.String(30),nullable=False),sa.Column("reason",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_lead_status_history_lead_id","lead_status_history",["lead_id"])
    op.create_table("follow_up_tasks",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("lead_id",sa.Integer(),sa.ForeignKey("leads.id"),nullable=False),sa.Column("idempotency_key",sa.String(120),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("subject",sa.String(200),nullable=False),sa.Column("content",sa.Text(),nullable=False),sa.Column("scheduled_at",sa.DateTime(timezone=True),nullable=False),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("attempts",sa.Integer(),nullable=False),sa.Column("max_attempts",sa.Integer(),nullable=False),sa.Column("lease_until",sa.DateTime(timezone=True)),sa.Column("failure_reason",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("lead_id","idempotency_key"));op.create_index("ix_follow_up_tasks_lead_id","follow_up_tasks",["lead_id"]);op.create_index("ix_follow_up_tasks_status","follow_up_tasks",["status"]);op.create_index("ix_follow_up_tasks_scheduled_at","follow_up_tasks",["scheduled_at"])
    op.create_table("email_deliveries",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("lead_id",sa.Integer(),sa.ForeignKey("leads.id")),sa.Column("follow_up_id",sa.Integer(),sa.ForeignKey("follow_up_tasks.id")),sa.Column("recipient_redacted",sa.String(220),nullable=False),sa.Column("provider",sa.String(30),nullable=False),sa.Column("provider_message_id",sa.String(255)),sa.Column("status",sa.String(30),nullable=False),sa.Column("attempts",sa.Integer(),nullable=False),sa.Column("error_type",sa.String(80)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_email_deliveries_lead_id","email_deliveries",["lead_id"])
    op.create_table("integration_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("provider",sa.String(40),nullable=False),sa.Column("operation",sa.String(80),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("lead_id",sa.Integer(),sa.ForeignKey("leads.id")),sa.Column("latency_ms",sa.Integer()),sa.Column("error_type",sa.String(80)),sa.Column("detail",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_integration_events_provider","integration_events",["provider"])
    with op.batch_alter_table("ai_decisions") as b:b.add_column(sa.Column("invocation_id",sa.Integer(),sa.ForeignKey("ai_invocations.id",name="fk_ai_decisions_invocation_id")));b.add_column(sa.Column("knowledge_refs",sa.JSON(),server_default="[]",nullable=False));b.add_column(sa.Column("question_reason",sa.Text()))
    with op.batch_alter_table("appointments") as b:b.add_column(sa.Column("slot_id",sa.Integer(),sa.ForeignKey("availability_slots.id",name="fk_appointments_slot_id")));b.add_column(sa.Column("external_provider",sa.String(30),server_default="local",nullable=False));b.add_column(sa.Column("external_event_id",sa.String(255)));b.add_column(sa.Column("external_url",sa.Text()));b.add_column(sa.Column("sync_status",sa.String(30),server_default="LocalOnly",nullable=False));b.add_column(sa.Column("failure_reason",sa.Text()));b.add_column(sa.Column("last_synced_at",sa.DateTime(timezone=True)));b.create_unique_constraint("uq_appointments_slot_id",["slot_id"])

def downgrade():
    with op.batch_alter_table("appointments") as b:
        b.drop_constraint("uq_appointments_slot_id",type_="unique")
        for c in ["last_synced_at","failure_reason","sync_status","external_url","external_event_id","external_provider","slot_id"]:b.drop_column(c)
    with op.batch_alter_table("ai_decisions") as b:
        for c in ["question_reason","knowledge_refs","invocation_id"]:b.drop_column(c)
    for name in ["integration_events","email_deliveries","follow_up_tasks","lead_status_history","ai_invocations","availability_slots"]:op.drop_table(name)
